name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v4

      - name: Comprovar Python
        run: python3 --version

      - name: Executar aplicació
        run: python3 app.py
